import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { NoteList } from "@/components/NoteList";
import { useNotes } from "@/utils/ContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { tags, notesWithTags } = useNotes();
  return <>
    <Head>
      <title>Typescript Markdown app</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* <div
      className={`${geistSans.variable} ${geistMono.variable}`}
    > */}
    <div style={{ height: "100vh" }}>
      <NoteList availableTags={tags} notes={notesWithTags} />
    </div>
    {/* </div > */}
  </>
}
